name: ci
on: push

jobs:
  build:
    name: 'build & test ${{ matrix.os }}'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          profile: minimal
          toolchain: stable
          components: 'rustfmt, clippy'
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - run: cargo fmt --all -- --check
      - run: cargo clippy
      - run: cargo build --release
      - run: cargo test --doc
      - run: cargo nextest run